name: opensearch # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap

version: '2.2.0' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'OpenSearch: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
    OpenSearch is a community-driven, Apache 2.0-licensed open source search and 
    analytics suite that makes it easy to ingest, search, visualize, and analyze data. 
    Developers build with OpenSearch for use cases such as application search, 
    log analytics, data observability, data ingestion, and more.

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots


assumes:
  - command-chain
  - snap-env
  - snapd2.56


system-usernames:
  snap_daemon: shared


plugs:
  procsys-read:
    interface: system-files
    read:
      - /proc/sys/vm/max_map_count
      - /proc/sys/vm/swappiness
      - /proc/sys/net/ipv4/tcp_retries2

hooks:
  install:
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/ops


environment:
  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs

  OPENSEARCH_HOME: ${SNAP_DATA}
  OPENSEARCH_JAVA_HOME: ${SNAP_DATA}/jdk
  OPENSEARCH_PATH_CONF: ${SNAP_COMMON}/config
  OPENSEARCH_TMPDIR: ${SNAP_COMMON}/tmp
  OPENSEARCH_PLUGINS: ${SNAP_DATA}/plugins


apps:
  daemon:
    daemon: simple
    install-mode: disable
    command-chain:
      - ops/sys/set-sys-config.sh
    command: ops/start.sh
    reload-command: ops/start.sh
    plugs:
      - network
      - network-bind
      - log-observe
      - mount-observe
      - process-control
      - procsys-read
    environment:
      OPS_ROOT: ${SNAP}/ops

  setup:
    command: ops/setup.sh
    environment:
      OPS_ROOT: ${SNAP}/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  plugin-add:
    command: ops/plugins/add.sh

  plugins-list:
    command: ops/plugins/list.sh

  plugins-remove:
    command: ops/plugins/remove.sh

parts:
#  python-requirements:
#    plugin: python
#    source: ./scripts
#    python-packages:
#      - ruamel.yaml

  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - util-linux
      - procps
      - libfreetype6
      - libpng16-16
      - libxrender1
      - libx11-6
      - libxext6
      - libxi6
      - libxtst6
      - libpsm-infinipath1
      - libboost-all-dev
      - libasound2
      - libpsm2-2-compat
      - libcrypt1
      - libexpat1
      - zlib1g

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${SNAPCRAFT_PART_INSTALL}/ops"
      
      rm -rf "${target_dir}"
      
      cp -r wrappers/. "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"

  opensearch:
    plugin: dump
    source: https://opensearch-builds.s3.eu-west-1.amazonaws.com/core/opensearch-${SNAPCRAFT_PROJECT_VERSION}-linux.tar.gz
    source-type: tar
